"""SHAP computation, global + path-stratified.

Manuscript reference: § 3.6 + Fig. 6 (path-stratified SHAP).

The path-stratified summary is the headline deliverable: for each
transition path k → j, which baseline covariates dominate the local
attribution? It is generated by grouping the SHAP value matrix by the
transition-path one-hot column that fired for each pixel.
"""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd


def compute_shap(model: Any, X: pd.DataFrame) -> np.ndarray:
    """TreeExplainer-based SHAP for a fitted XGBRegressor. Returns
    ndarray of shape (n_samples, n_features)."""
    import shap
    explainer = shap.TreeExplainer(model)
    values = explainer.shap_values(X)
    if isinstance(values, list):  # multi-output safety
        values = values[0]
    return np.asarray(values)


def global_summary(shap_values: np.ndarray,
                   feature_names: list[str]) -> pd.DataFrame:
    """Mean |SHAP| per feature, sorted descending — the global ranking."""
    mean_abs = np.abs(shap_values).mean(axis=0)
    return (pd.DataFrame({"feature": feature_names, "mean_abs_shap": mean_abs})
              .sort_values("mean_abs_shap", ascending=False)
              .reset_index(drop=True))


def path_stratified_shap(shap_values: np.ndarray, X: pd.DataFrame,
                         path_code: pd.Series) -> pd.DataFrame:
    """Mean |SHAP| per feature, stratified by transition path.

    Long-format DataFrame with columns: path, feature, mean_abs_shap.
    Used to drive Fig. 6b (path × feature heatmap) and the Discussion
    paragraph on which baseline conditions modulate each pathway.
    """
    if len(path_code) != shap_values.shape[0]:
        raise ValueError("path_code length must equal shap_values rows")
    if X.shape[1] != shap_values.shape[1]:
        raise ValueError("X columns must equal shap_values columns")

    paths = path_code.reset_index(drop=True)
    abs_shap = np.abs(shap_values)
    rows = []
    feature_names = list(X.columns)
    for p, idx in paths.groupby(paths).groups.items():
        idx_arr = np.asarray(idx, dtype=int)
        mean_abs = abs_shap[idx_arr].mean(axis=0)
        for f_name, v in zip(feature_names, mean_abs):
            rows.append({"path": p, "feature": f_name, "mean_abs_shap": float(v)})
    return pd.DataFrame(rows)


def top_modulators_per_path(stratified: pd.DataFrame,
                            exclude_path_onehots: bool = True,
                            top_n: int = 3) -> pd.DataFrame:
    """For each path, return the top-N features by mean |SHAP|, optionally
    excluding the transition-path one-hot columns themselves so the
    answer reads as "which **baseline** conditions modulate this path"."""
    df = stratified.copy()
    if exclude_path_onehots:
        df = df[~df["feature"].astype(str).str.startswith("path_")]
    df = (df.sort_values(["path", "mean_abs_shap"], ascending=[True, False])
            .groupby("path", group_keys=False)
            .head(top_n)
            .reset_index(drop=True))
    df["rank"] = df.groupby("path").cumcount() + 1
    return df


def shap_for_hsi_paths(stratified: pd.DataFrame,
                       headline_paths: list[Any]) -> pd.DataFrame:
    """Subset to the α/β headline paths (Q4 central claim) for direct
    inclusion in the Results paragraph."""
    return stratified[stratified["path"].isin(headline_paths)].copy()
